source 'https://rubygems.org'

gem 'rails', '~>2.3'
gem 'activerecord-lazy-attributes'
gem 'mysql', '~>2.8'
gem 'json'
gem 'mongrel'
gem 'rake'
gem 'rspec-rails'
gem 'technicalpickles-jeweler'
gem 'rdoc', '>=2.4.2'
