source 'https://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '~>2.3'
gem 'activerecord-lazy-attributes'
gem 'mysql', '~>2.8'
gem 'json'
gem 'mongrel'
gem 'infopark-politics'

gem 'rake'
gem 'rspec-rails'
gem 'technicalpickles-jeweler'
gem 'rdoc', '>=2.4.2'

gem 'cucumber'
gem 'sqlite3'
gem 'spork'
gem 'cucumber-rails', '>= 0.2.2'
gem 'database_cleaner', '>= 0.2.3'
gem 'webrat', '>= 0.6.0'
